---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность искать товары по категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - На странице корзины пользователь может удалить товар из корзины
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты
  - На странице корзины пользователь может вернуться к выбору товаров в каталоге
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Корзина будет хранится в сессии браузера
non-functional:
  - Сайт должен быть SPA приложением
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Вывод товаров в каталоге должен осуществляться постранично
implicit:
  - Поиск по ключевому слову должен успешно осуществляться на русском и английском языках
  - При фильтрации товаров пользователь должен иметь возможность отменить все применённые фильтры
  - При выходе из просмотра товара, фильтры примененные в каталоге не должны сбиваться
  - Пользователь должен иметь возможность перемещаться по страницам каталога с помощью кнопок навигации
  - Пользователь не должен иметь возможность редактировать данные товаров
  - Пользователь должен иметь возможность быстро вернуться на главную страницу сайта в любой момент
  - Добавить товар в корзину можно как из каталога, так и при подробном просмотре карточки товара
  - При смене языка не должна сбиваться верстка сайта
  - Должна присутствовать форма сбора отзывов о товаре, для формирования его рейтинга
  - Фильтр товаров по цене не должен давать вводить отрицательные значения цены
  - Используемые фильтры не должны противоречить друг другу
  - При отсутствии товара в наличии нельзя добавить его в корзину
  - На любой странице каталога пользователю должны быть доступны все возможные фильтры
  - При открытии сайта, пользователя должны спросить согласие на использование Cookie файлов
  - Возможно применение нескольких доступных фильтров одновременно
