---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрировать учетную запись
  - Форма регистрации должна иметь поля для ввода имени пользователя, пароля, проверки правильности пароля, электронной почты и номера телефона
  - Поле ввода имени пользователя должно иметь ограничение по минимальному и максимальному возможному количеству символов
  - Пароль не должен быть меньше необходимого числа символов
  - Пароли в полях ввода пороля и проверке правильности пароля должны совпадать
  - Должна присутствовать валидация адреса электронной почты
  - В поле ввода номера телефона можно указывать только цифры
  - В поле ввода номера телефона должен быть реализован выпадающий список с кодами стран
  - Каждое поле ввода должно выводить соответствующие ошибки под строкой ввода, при вводе некорректных данных
  - При указании некорректных данных в форме регистрации кнопка "Зарегистрироваться" блокируется
  - Нельзя зарегистрировать уже существующего пользователя
  - Пользователь должен иметь возможность войти в существующую учетную запись
  - Форма входа должна иметь поля для ввода адреса электронной почты и пароля
  - При указании неверного адреса электронной почты и/или пароля должно выводится сообщение об ошибке входа
  - Осуществлять добавление товара в корзину и оформление заказа может только авторизованный пользователь
  - Сайт должен поддерживать интеграцию систем онлайн оплаты
  - Пользователь должен иметь возможность отслеживать статус и подробную информацию о своих заказах
  - Необходима форма сбора отзывов о товаре, чтобы формировать рейтинг товаров
  - Шапка сайта должна иметь кнопки перенапрвляющие пользователя на необходимые ему разделы
  - Указанные цены товаров не могут иметь отрицательные значения
  - При возникновении ошибок в работе сайт должен перенаправлять пользователя на страницу с кодом ошибки
